POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Golden Troll",
  "author": "O.S. Leshyev",
  "url": "about:blank",
  "likes": 100
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "author": "O.S. Leshyev",
  "likes": 100
}